name: Pics repository sync
on:
  push:
    branches:
      - main
jobs:
  commit:
    runs-on: ubuntu-latest
    env:
      REMOTE: YGOProjectUnderground/Nexus.git
      REPO_NAME: Nexus
      DESTINATION: Nexus/pics
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: Clone destination repository
      run: |
        cd $HOME
        git clone https://${{ secrets.DEPLOY_TOKEN }}@github.com/$REMOTE
        mkdir -p $DESTINATION
    - name: Install Pillow
      run: pip install Pillow
    - name: Process and copy images
      id: copy
      run: |
        c1grep() { grep "$@" || test $? = 1; }
        if [ $(git rev-list --count HEAD) -eq 1 ]; then
          ADDED=$(find . -type f \( -name "*.jpg" -o -name "*.png" \) | c1grep -vP "(^|/)\..*")
        else
          ADDED=$(git diff-tree --no-commit-id --name-only -r HEAD --diff-filter=AM | c1grep -vP "(^|/)\..*" | c1grep -P "\.(jpg|png)$")
        fi
        
        if [[ "$ADDED" ]]; then
          echo "$ADDED" | while IFS= read -r file; do
            python ./.github/process_image.py "$file" "$HOME/$DESTINATION"
          done
        fi
    - name: Remove deleted files
      run: |
        if [[ -f $HOME/$DESTINATION/VERSION ]]; then
          LAST_SHA=$(cat $HOME/$DESTINATION/VERSION)
          REMOVED=$(git diff --name-only --no-renames --diff-filter=D $LAST_SHA | c1grep -P "\.(jpg|png)$")
          if [[ "$REMOVED" ]]; then
            cd $HOME/$DESTINATION
            echo "$REMOVED" | while IFS= read -r file; do
              dest_file="${file%.*}.jpg"
              git rm -rf --ignore-unmatch "$dest_file"
            done
          fi
        fi
    - name: Commit and push with original metadata
      run: |
        MESSAGE=$(git log -1 --pretty=%B)
        AUTHOR=$(git log -1 --pretty=format:'%an')
        EMAIL=$(git log -1 --pretty=format:'%ae')
        COMMITTER=$(git log -1 --pretty=format:'%cn')
        CEMAIL=$(git log -1 --pretty=format:'%ce')
        cd $HOME/$DESTINATION
        echo $GITHUB_SHA > VERSION
        git config user.email "$CEMAIL"
        git config user.name "$COMMITTER"
        git add -A .
        if [[ $(git status --porcelain) ]]; then
          git commit --author="$AUTHOR <$EMAIL>" -m "$MESSAGE"
          git push
        fi